more broker-config.yml
# Uncomment and modify as needed
config:
  #  cache_path: ${britive.broker.action.command.cache} # default to ./cache if not provided
  bootstrap:
    #    execution_environment: /bin/sh -c "sudo -E <BRITIVE_BOOTSTRAP_SCRIPT>" # optional
    #    scripts_path: ${britive.broker.scripts.path}  # default to ./bootstrap if not provided
    #    scripts_path: scripts
    tenant_subdomain: se-learn
    #    authentication_token_generator: ${britive.broker.authentication.token.script}  # optional
    authentication_token: ShahzadAliT0k3nfJQkHoFvCl+vleq5JACCESSbr0Ker=
    broker_name_generator: broker-name-generator.sh
    #    resources_generator: ${britive.broker.resources.script}
    #  http_proxy:  # optional, if not specified do not use http proxy for connecting
    #    host: localhost      # required
    #    port: 8080           # required
    #    username: userA      # optional: if this or password not specified authorization type is None
    #    password: passwordA  # optional: if this or username not specified authorization type is None
    #    connection_type: [Legacy | Forwarding | Tunneling]   # optional defaults to Tunneling if not specified
    #
    # The resource types supported by this broker
resource_types:
  VyOS-Router:
    JITAdminPermission:
      max_supported_version: local
      checkout_script: /Users/shahzadali/britive-broker-scripts/vyos_router_add_jit_user_checkout.sh
      checkin_script: /Users/shahzadali/britive-broker-scripts/vyos_router_delete_jit_user_checkin.sh
    # Following line must match with "Resource Types" configuration in the UI
  Britive.Introduction:
    PrintHelloWorldPermission:
      max_supported_version: local
      checkout_script: /Users/shahzadali/britive-broker-scripts/britive_intro_checkout.sh
      checkin_script: /Users/shahzadali/britive-broker-scripts/britive_intro_checkin.sh
  Network-Firewall:
    Fortinet_ZSP_Permission:
      max_supported_version: local
      checkout_script: /Users/shahzadali/britive-broker-scripts/FortiManager_checkout.sh
      checkin_script: /Users/shahzadali/britive-broker-scripts/FortiManager_checkin.sh
